# Proxy: Netlify -> Render
[[redirects]]
  from = "/api/*"
  to = "https://gt-shop-backend.onrender.com/api/:splat"
  status = 200
  force = true

# (opțional) migrare vechi /frontend/* -> /:splat, vezi pasul 1
[[redirects]]
  from = "/frontend/*"
  to = "/:splat"
  status = 200

# SPA fallback (ține-o ultima)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200